rally:
  uri: rally1.rallydev.com
  apikey: _qy1urW6ySCCCwGTvKjeiYFZbSBl0UQ2g2TQ51KQQEU
  project: Assist
  workspace: Ford
  board:
    cycleTime:
      startState: In Progress
      endState: Deployed

