rally:
  uri: rally1.rallydev.com
  apikey: _qy1urW6ySCCCwGTvKjeiYFZbSBl0UQ2g2TQ51KQQEU
  proxy: proxyvipecc.nb.ford.com:83
  project: Consumer Relationship
  workspace: Ford
  board:
    cycleTime:
      startState: IN-PROGRESS
      endState: DONE [DEPLOYED TO PROD]
    story:
      creationDate: 2019-01-01

